[package]
name = "moments-aura"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread", "fs"] }
serde = { version = "1.0.228", features = ["derive"] }
axum = { version = "0.8.6", features = ["multipart"] }
toml = "0.9.8"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
bytes = "1.10.1"
object_store = "0.12.4"
serde_json = "1.0.145"

[dev-dependencies]
tempfile = "3.10"
